services:
  - name: youtube-downloader
    type: web
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main2:app"
    envVars:
      - key: PORT
        value: 10000
